apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata: 
	name: my-app-java
	namespace: my-project
spec:
	replicas: 1
	selector:
		matchLabels:
		app: my-app-java
	template:
		metadata:
			labels:
				app: my-app-java
	spec:
		containers:
			- name: my-app-java
			- image: ridlwan/simple-java-springboot:2.0
			ports:
			- containerPort: 8282